### ISSUE TITLE
Seeding not working

### ISSUE THREAD

**Issue by cdelgadob** [99xt/serverless-dynamodb-local#121]
An error is thrown when trying to seed the local DynamoDB. The error is:
```
TypeError: Cannot read property 'dynamodb' of undefined
    at ServerlessDynamodbLocal.get seedSources [as seedSources] (/Users/carlos/Documents/project/apollo-server/node_modules/serverless-dynamodb-local/index.js:182:43)
    at ServerlessDynamodbLocal.seedHandler (/Users/carlos/Documents/project/apollo-server/node_modules/serverless-dynamodb-local/index.js:127:33)
    at BbPromise.resolve.then.then (/Users/carlos/Documents/project/apollo-server/node_modules/serverless-dynamodb-local/index.js:158:42)
```
I'm launching it with this command: `sls offline start --migrate --seed=test`

The configuration extract in `serverless.yml` is:
```  
[...]
    custom:
    dynamodb:
      start:
        port: 8000
        inMemory: true
        migrate: true
        seed: true
      seed:
        test:
          sources:
            - table: auth_perms
              sources: [./auth_perms_seed.json]
    [...]
```

This is happening in plugin versions 0.2.24, 0.2.22
