### ISSUE TITLE
[0.2.36] 'sls dynamodb install' shows nothing

### ISSUE THREAD

**Issue by kdby-io** [99xt/serverless-dynamodb-local#195]
**Actual Behaviour**
nothing. But downgrading to 0.2.35 can works what I expect.

**Expected Behaviour**
Installing dynamodb local.

**Steps to reproduce it**
```
yarn add -D serverless-dynamodb-local
sls dynamodb install
```

**Comment by jonaswitt** [comment]
+1 same problem here. The code from #190 does not yet exhibit this problem, so it must be caused by either https://github.com/99xt/serverless-dynamodb-local/commit/2d32f2f8e179838e0adb8bc74df9f69dd7d7214c or https://github.com/99xt/serverless-dynamodb-local/commit/e6ce9b6be4007f6ef88dd1ed49059a096c7bd0ce (only two commits before the 0.2.36 release)

**Comment by sohailalam2** [comment]
@AshanFernando Any ETA when and how this might get resolved?

**Comment by espozbob** [comment]
+1 same problem here. 
I'm downgrading to 0.2.35...

**Comment by sohailalam2** [comment]
I tried v0.2.35 but this is not working either. Unfortunately for some spooky reasons, I am not able to install dynamodb with any version whatsoever. I tried several previous versions. 

@espozbob could you please confirm if you are able to install it even after deleting the node_modules directory and then installing the packages?

FYI, I am using 

```yml
provider:
  name: aws
  runtime: nodejs8.10
  stage: dev
  region: eu-central-1

custom:
  dynamodb:
    start:
      port: 8000
      inMemory: true
      region: eu-central-1
  serverless-offline:
    port: 8080
```
