### ISSUE TITLE
Migrations not working

### ISSUE THREAD

**Issue by salmankhann** [99xt/serverless-dynamodb-local#202]
**Actual Behaviour**

Running Serverless offline start is not running local DynamoDB migrations.

**Expected Behaviour**

Running Serverless offline start should run local DynamoDB migrations

**Steps to reproduce it**

I have the following serverless.yaml file
```
service: candidate-service 
frameworkVersion: ">=1.1.0 <2.0.0"

provider:
  name: aws
  runtime: nodejs8.10
  stage: dev
  region: us-east-1

  environment:
    CANDIDATE_TABLE: ${self:service}-${opt:stage, self:provider.stage}
    CANDIDATE_EMAIL_TABLE: "candidate-email-${opt:stage, self:provider.stage}"
  
  iamRoleStatements:
    - Effect: Allow
      Action:
        - dynamodb:Query
        - dynamodb:Scan
        - dynamodb:GetItem
        - dynamodb:PutItem
      Resource: "*"
  
  resources:
    Resources:
      CandidateDynamoDbTable:
        Type: "AWS::DynamoDB::Table"
        DeletionPolicy: Retain
        Properties:
          AttributeDefinitions:
            - AttributeName: "id"
              AttributeType: "S"
          KeySchema:
            - AttributeName: "id"
              KeyType: "HASH"
          ProvisionedThroughput:
            ReadCapacityUnits: 1
            WriteCapacityUnits: 1
          StreamSpecification:
            SteamViewType: "NEW_AND_OLD_IMAGES"
          TableName: ${self:provider.environment.CANDIDATE_TABLE}
            

functions:
  candidateSubmission:
    handler: api/candidate.submit
    memorySize: 128
    description: Submit candidate information and starts interview process
    events:
      - http:
          path: candidates
          method: post
  hello:
    handler: handler.hello
    memorySize: 128
    description: Submit candidate information and starts interview process
    events:
      - http:
          path: /
          method: get

package:
  include:
    - handler.ts
    - api/**
  exclude:
    - node_modules/**/*
  #excludeDevDependencies: true

plugins:
  - serverless-plugin-typescript
  - serverless-dynamodb-local
  - serverless-offline

custom:
  dynamodb: 
    start:
      port: 8000
      inMemory: true
      migrate: true
```

upon running ```serverless offline start```, it prints out the following
```
Serverless: Compiling with Typescript...
Serverless: Typescript compiled.
Serverless: Watching typescript files...
Dynamodb Local Started, Visit: http://localhost:8000/shell
Serverless: Starting Offline: undefined/undefined.

Serverless: Routes for candidateSubmission:
Serverless: POST /candidates

Serverless: Routes for hello:
Serverless: GET /

Serverless: Offline listening on http://localhost:3000
```

Why is the migration not being performed? Currently I have no tables and I need to create initial tables and migrations should do that. What could be wrong?

I am running version 0.2.30. I rolled back to this version because 0.2.36 has other issues. What could be wrong? 

**Would you like to work on the issue?**

Someone else because I do not have much knowledge of this codebase
