### ISSUE TITLE
Doesn't Work With Custom Properties Dynamically Loaded

### ISSUE THREAD

**Issue by paulcruseSG** [99xt/serverless-dynamodb-local#205]
**Actual Behaviour**

The default parameters are being applied (no migrate, port 8000, etc) 

**Expected Behaviour**

I am dynamically loading a custom file into my serverless.yml like this:

```yml
# the serverless file
custom: ${file(./sls_custom/${opt:sls_custom, 'local'}.yml):custom}
```

Then in my custom file I am using:
```yml
# the custom file
custom:
    serverless-offline:
        port: 9000
        prefix: companies
        stage: local
        region: us-east-1
        noAuth: true
    dynamodb:
        start:
            port: 4000
            inMemory: false
            migrate: true
            optimizeDbBeforeStartup: true
```

But when I run my local lambda I get:
```bash
serverless offline start --sls_custom local
Dynamodb Local Started, Visit: http://localhost:8000/shell
```

Can anyone give me any tips as to why this is happening?
