### ISSUE TITLE
dynamodb cors in serverless.yml

### ISSUE THREAD

**Issue by dcarr178** [99xt/serverless-dynamodb-local#206]
I cannot get dynamodb local to run in cors mode when starting it using `serverless offline start`.

serverless.yml:
```
plugins:
  - serverless-dynamodb-local
  - serverless-offline

custom:
  dynamodb:
    start:
      migrate: true
      cors: true
```

```
$ serverless offline start
Dynamodb Local Started, Visit: http://localhost:8000/shell
```
My dynamo tables get created just fine and dynamodb runs fine on port 8000 but when I try to make requests to dynamodb local from my PWA running in a browser it says 
```
Access to XMLHttpRequest at 'http://localhost:8000/' from origin 'http://localhost:4200' has been blocked by CORS policy: No 'Access-Control-Allow-Origin' header is present on the requested resource.
```
Is cors: true configured correctly in my serverless.yml snippet above? Is starting dynamodb local with cors support (-c) supported?

**Comment by dcarr178** [comment]
Nevermind - this looks like a browser bug. Dynamodb local is showing cors support but I have an error in my network request so dynamo is returning status code 400 which chrome is assuming is a cors problem but it isn't.

**Comment by dcarr178** [comment]
The serverless.yml configuration that allows cors is 
```
custom:
  dynamodb:
    start:
      migrate: true
    cors: true
```
Setting cors = true at the right indentation level was tricky and required trial & error. I'm re-opening the issue in hopes that you can include this in your documentation in the future.
