### ISSUE TITLE
Using dynamodb on local network with serverless offline

### ISSUE THREAD

**Issue by michinamibia** [99xt/serverless-dynamodb-local#224]
I have dynamodb local running on a network server with IP 192.168.0.200.

My serverless.yml file is setup as follows:

```
plugins:
  - serverless-dynamodb-local
  - serverless-offline
custom:
  dynamodb:
    start:
      host: 192.168.0.200
      noStart: true
      migrate: true
```

When running `serverless offline start` I can see that the output says that the migration worked and the table was created and on a rerun it says that the table already exists.

But when I actually check the dynamodb database on the server i see no tables. Also using serverless-dynamodb-client to query the db i get "Cannot do operations on a non-existent table"

It seems to me that the migration does not actually run on the 192.168.0.200 server but locally.
