### ISSUE TITLE
0.2.38 breaking change: DynamoDB Local is not available for stage

### ISSUE THREAD

**Issue by aaronjensen** [99xt/serverless-dynamodb-local#225]
It looks like you released a new patch version and I don't see any release notes or instructions. This change was a breaking change for us in CI. We now get:

**Actual Behaviour**

When running:

```
serverless dynamodb migrate --stage test
```

We get:

```
Serverless: Skipping migration: DynamoDB Local is not available for stage: test
```

**Expected Behaviour**

It would work as it did before or be released as a new minor or major version with migration instructions.

**Steps to reproduce it**

See above

**LogCat for the issue**

See above

**Screenshots of the issue**

None

**Would you like to work on the issue?**

No thank you

**Comment by jacqueslorentz** [comment]
Same problem when starting serverless offline with dynamodb custom config:
```yaml
dynamodb:
    start:
      port: 8002
      inMemory: true
      migrate: true
```

When `serverless offline start` I get the error `Serverless: Skipping start: DynamoDB Local is not available for stage: dev`

Thanks!

**Comment by karticus** [comment]
looks like this pr:  https://github.com/99xt/serverless-dynamodb-local/commit/5e53d7622d901bc05515135cd91de04a6680d38e

@rehrumesh any ideas?

**Comment by rhnorskov** [comment]
Solved it by adding the stage to the stages whitelist.

```
custom:
  dynamodb:
    stages:
      - test
```

**Comment by manoj-bandara** [comment]
stages:  direction works

**Comment by mlg-rbalhorn** [comment]
seems this bug has bitten our developers as well.

So we now have to whitelist all of our stages or just our local ones?

**Comment by samscarsella** [comment]
I started getting this error with 0.2.37 this morning, and the whitelist strategy from @rhnorskov worked for me. One slight difference from the OP is that I'm running `sls offline start` and was getting `Skipping start: DynamoDB Local is not available for stage: dev`.

**Comment by davecarlson** [comment]
@99xt - there is nothing in this repo about the commit that caused 0.2.38 - can you advise ?

**Comment by honasassa** [comment]
```yaml
custom:
  dynamodb:
    stages:
      - test
```

works but in my case, had to remove and reinstall dynamodb.

**Comment by liorsuperquery** [comment]
```
custom:
  dynamodb:
    stages:
      - test
```

works for me, thanks

**Comment by cecton** [comment]
For all stages:
```
custom:
  dynamodb:
    stages:
      - ${self:provider.stage}
```
