### ISSUE TITLE
Is time to live supported by the plugin?

### ISSUE THREAD

**Issue by danielo515** [99xt/serverless-dynamodb-local#238]
**Actual Behaviour**

Seems that nothing happens

**Expected Behaviour**

I expect expired records to be deleted

**Steps to reproduce it**

Add this to the database to enable the expire time:

```
  Table:
    Type: 'AWS::DynamoDB::Table'
    Properties:
      TimeToLiveSpecification:
        AttributeName: expiresAt
        Enabled: true
```

I am wondering if the TimeToLive feature of DynamoDb is supposed to work locally on this plugin.
