### ISSUE TITLE
Cannot seed dynamodb

### ISSUE THREAD

**Issue by tonytangdev** [99xt/serverless-dynamodb-local#244]
**Actual Behaviour**

In my serverless.yml, I enabled the seeding option and I provided the path to my json file. But I get an error when I try to run `serverless offline start`.

The only plugins I use are **serverless-dynamodb-local** and **serverless-offline**.

**Expected Behaviour**

The plugin should be able to seed dynamodb based on the documentation : https://github.com/99xt/serverless-dynamodb-local#seeding-sls-dynamodb-seed

**Steps to reproduce it**

A snippet of my serverless.yml: 
```
plugins:
  - serverless-dynamodb-local
  - serverless-offline

custom:
  dynamodb:
    start:
      port: 8000
      inMemory: true
      migrate: true
      seed: true
    migration:
      dir: offline/migrations
    seed:
      test:
        - table: ${self:provider.environment.DYNAMODB_TABLE}
          sources: [./offline/seed/sample-awesome-facts.json]
    stages:
      - dev

resources:
  Resources:
    TodosDynamoDbTable:
      Type: 'AWS::DynamoDB::Table'
      DeletionPolicy: Retain
      Properties:
        AttributeDefinitions:
          - AttributeName: uuid
            AttributeType: S
        KeySchema:
          - AttributeName: uuid
            KeyType: HASH
        BillingMode: PAY_PER_REQUEST
        TableName: ${self:provider.environment.DYNAMODB_TABLE}
```

Run the command `serverless offline start --migrate`

**LogCat for the issue**

```
TypeError: Cannot read property 'table' of undefined
      at /mnt/f/Workspace/Github/tonytangdev/wow-awesome-serverless/lambda/node_modules/serverless-dynamodb-local/index.js:206:29
  From previous event:
      at PluginManager.invoke (/usr/lib/node_modules/serverless/lib/classes/PluginManager.js:490:22)
      at /usr/lib/node_modules/serverless/lib/classes/PluginManager.js:525:24
  From previous event:
      at PluginManager.run (/usr/lib/node_modules/serverless/lib/classes/PluginManager.js:525:8)
      at /usr/lib/node_modules/serverless/lib/Serverless.js:133:33
      at processImmediate (internal/timers.js:456:21)
      at process.topLevelDomainCallback (domain.js:137:15)
  From previous event:
      at Serverless.run (/usr/lib/node_modules/serverless/lib/Serverless.js:120:74)
      at /usr/lib/node_modules/serverless/bin/serverless.js:82:30
      at /usr/lib/node_modules/serverless/node_modules/graceful-fs/graceful-fs.js:136:16
      at /usr/lib/node_modules/serverless/node_modules/graceful-fs/graceful-fs.js:57:14
      at FSReqCallback.oncomplete (fs.js:154:23)
  From previous event:
      at /usr/lib/node_modules/serverless/bin/serverless.js:82:8
      at processImmediate (internal/timers.js:456:21)
      at process.topLevelDomainCallback (domain.js:137:15)
  From previous event:
      at Object.<anonymous> (/usr/lib/node_modules/serverless/bin/serverless.js:71:4)
      at Module._compile (internal/modules/cjs/loader.js:1151:30)
      at Object.Module._extensions..js (internal/modules/cjs/loader.js:1171:10)
      at Module.load (internal/modules/cjs/loader.js:1000:32)
      at Function.Module._load (internal/modules/cjs/loader.js:899:14)
      at Function.executeUserEntryPoint [as runMain] (internal/modules/run_main.js:71:12)
      at internal/main/run_main_module.js:17:47
```

**Would you like to work on the issue?**

In index.js, line 323 : `const sourcesByCategory = categories.map((category) => seedConfig[category].sources);`

We are trying to get sources from `seedConfig[category]` but it doesn't exist as `seedConfig[category]` is an array that looks like :

```
[
  {
    table: 'awesome-facts-dev',
    sources: [ './offline/seed/sample-awesome-facts.json' ]
  }
]
```

I already worked on it and I'm going to create a pull request.

**Comment by tonytangdev** [comment]
Turns out I just configuration is wrong.

```
custom:
  dynamodb:
    start:
      port: 8000
      inMemory: true
      migrate: true
      seed: true
    migration:
      dir: offline/migrations
    seed:
      test:
        sources:  # I forgot this one
          - table: ${self:provider.environment.DYNAMODB_TABLE}
            sources: [./offline/seed/sample-awesome-facts.json]
    stages:
      - dev
```
