### ISSUE TITLE
Migrate doesn't work if referencing CloudFormation variables

### ISSUE THREAD

**Issue by nj-io** [99xt/serverless-dynamodb-local#248]
**Actual Behaviour**

As title says, if I use a ```${cf:}``` reference, a table will not be successfully created

**Expected Behaviour**

Create a table locally

**Steps to reproduce it**

```
provider:
  name: aws
  stage: dev
  runtime: nodejs12.x
  region: us-east-1
  environment:
    DB_USERS_TABLE: ${cf:${self:service}-${self:provider.stage}.DbUsersTable}

resources: 
    Outputs:
      DbUsersTable:
         Value:
           Ref: usersTable
         Export:
           Name: ${self:service}-${self:provider.stage,dev}-usersTable

custom:
  dynamodb:
    start:
      port: 8000
      inMemory: true
      heapInitial: 200m
      heapMax: 1g
      migrate: true
      convertEmptyValues: true
      seed: true
      dbPath: ./
```

Any help or advise would be appreciated. Thanks
