### ISSUE TITLE
Buggy behaviour when creating table

### ISSUE THREAD

**Issue by nj-io** [99xt/serverless-dynamodb-local#249]
**Actual Behaviour**

Depending on the TableName, the table sometimes shows up in shell, sometimes doesn't

**Expected Behaviour**

TableName should appear in localhost:8000/shell regardless of naming

**Steps to reproduce it**

serverless.yml:

```
resources:
  Resources:
    usersTable:
      Type: AWS::DynamoDB::Table
      Properties:
        # TableName: ${self:provider.environment.DB_USERS_TABLE}
        # TableName: 'eeee' doesn't work
        # TableName: 'xxx'
        # TableName: 'tableName1234' doesn't work
        # TableName: 'uuuuu-uuuu'
        # TableName: 'ddddddd' doesn't work
        # TableName: 'bbbb' doesn't work
        # TableName: 'uuu'
        # TableName: '1234' doesn't work
        # TableName: usersTable
        # TableName: usersTable1234
        # TableName: usersTable1234-backend-poc-dev-usersTable-1W86P86DZETOP
        # TableName: db-backend-poc-dev-usersTable-1W86P86DZETOP doesn't work
        # TableName: usersTable-db-backend-poc-dev-usersTable-1W86P86DZETOP
        # doesn't work
        # TableName: aaa-usersTable
        TableName: yyy
        # TableName: zzz

custom:
  dynamodb:
    start:
      port: 8000
      inMemory: true
      heapInitial: 200m
      heapMax: 1g
      migrate: true
      convertEmptyValues: true
      seed: true
      dbPath: ./
    stages:
      - dev
```
package.json
```
  "devDependencies": {
    "aws-sdk": "^2.639.0",
    "serverless-dynamodb-local": "^0.2.39",
    "serverless-offline": "^5.12.1",
}
```

**LogCat for the issue**

Provide logs for the crash here

**Screenshots of the issue**

Where-ever possible attach a screenshot of the issue.

**Would you like to work on the issue?**

Don't know how
