### ISSUE TITLE
Table Items not persisted across server starts

### ISSUE THREAD

**Issue by lmuntaner** [99xt/serverless-dynamodb-local#253]
**Actual Behaviour**

Configuration in `serverless.yml`.

```
  dynamodb:
    start:
      port: 8089
      migrate: true
      inMemory: false
    stages:
      - ${self:provider.stage}
```

After closing and starting up again serverless offline the database is restarted and all data is lost. As if it was using `inMemory`. But `inMemory` is set to `false`.

It seems that the tables are created after every `sls offline start`.

This also happens with `sls dynamodb start`.

**Expected Behaviour**

`sls offline start` does not create tables if they already exist.

**Steps to reproduce it**

1. Start offline server
2. Insert items into DynamoDB
3. Close server
4. Start offline server
5. Scan table -> Table is empty

**LogCat for the issue**

None

**Screenshots of the issue**

None

**Would you like to work on the issue?**

I would love to, but it seems that there is something I am doing wrong. It doesn't seem a bug in the library.
