### ISSUE TITLE
Not starting DDB-local when running sls offline

### ISSUE THREAD

**Issue by revmischa** [99xt/serverless-dynamodb-local#256]
**Actual Behaviour**

Not starting local dynamo when running `sls offline`

**Steps to reproduce it**

```yaml
plugins:
  - serverless-plugin-typescript
  - serverless-plugin-optimize
  - serverless-pseudo-parameters
  - serverless-dynamodb-local
  - serverless-offline

custom:
  serverless-offline:
    useChildProcesses: true
  dynamodb:
    start: # why doesn't this automatically start?
      port: 4455
      # inMemory: true
      migrate: true
    stages:
      - dev
```

**LogCat for the issue**

Provide logs for the crash here
```
❯ sls offline
Serverless: Running "serverless" installed locally (in service node_modules)
Serverless: Compiling with Typescript...
Serverless: Using local tsconfig.json
Serverless: Typescript compiled.
Serverless: Watching typescript files...
offline: Starting Offline: dev/eu-west-1.
offline: Offline [http for lambda] listening on http://localhost:3002

   ┌─────────────────────────────────────────────────────────────────────────────────┐
   │                                                                                 │
   │   POST | http://localhost:3000/dev......  │                                                                                 │
   └─────────────────────────────────────────────────────────────────────────────────┘

offline: [HTTP] server ready: http://localhost:3000 🚀
offline:
offline: Enter "rp" to replay the last request
```

**Would you like to work on the issue?**

Not sure where to start

**Comment by mdepascale** [comment]
Alright finally I found out a method (it's very raw) to locally test dynamodb

I have this version:
`"serverless-dynamodb-local": "^0.2.37"`

serverless.yml custom parameters:
```
dynamodb:
  stages:
    - ${self:provider.stage}
  start:
    port: 8000
    inMemory: true
    migrate: true
    #noStart: true
  migration:
    dir: offline/migrations
```

My lambda runs this configuration:

```
let options = {};

if (process.env.IS_OFFLINE) {
    options = {
        endpoint: 'http://localhost:8000',
        region: 'localhost'
    }
}

const dynamodb = new DynamoDB.DocumentClient(options);
```


after that I run ` serverless dynamodb start --stage local` in one shell 
and `sls offline --stage local` in the other one

This works, it's the first solution that worked for me, I will try to improve it in the meantime you could use this one
