### ISSUE TITLE
Every time I restart dynamodb local and run "sls dynamodb start" the content of the DB is wiped

### ISSUE THREAD

**Issue by nelsongallardo** [99xt/serverless-dynamodb-local#259]
**Actual Behaviour**

i run `sls dynamodb start` - I populate the database, I stop dynamodb local and run it again, and table is recreated and content wiped.

This is my .yml configuration

```
dynamodb:
    start:
      migrate: true
      inMemory: false
   stages:
      - ${self:provider.stage}

```
**Expected Behaviour**

Given that `inMemory:` is set to **false** I would expect the data to be written to disk and next time I restart the server the data should be there.

**Steps to reproduce it**

Just start server with `sls dynamodb start` - populate some data, and restart the server and data will be gone.
