### ISSUE TITLE
DynamoDB Local throwing NetworkingError

### ISSUE THREAD

**Issue by pflugs30** [99xt/serverless-dynamodb-local#264]
I'm trying to use serverless-dynamodb-local to start a local DynamoDB instance and seed two tables with data from two JSON files.

**package.json**
```
{
  "name": "test",
  "version": "0.0.0",
  "private": true,
  "scripts": {
    "start": "serverless dynamodb install && serverless offline start"
  },
  "dependencies": {},
  "devDependencies": {
    "aws-sdk": "^2.407.0",
    "serverless": "^2.31.0",
    "serverless-dynamodb-client": "^0.0.2",
    "serverless-dynamodb-local": "^0.2.39",
    "serverless-offline": "^6.9.0"
  }
}
```

**serverless.yml**
```
service: dynamodb-local-test

frameworkVersion: ">=2.0.0"

provider:
  name: aws
  runtime: nodejs12.x
  stage: dev
  region: us-east-2

plugins:
  - serverless-dynamodb-local
  - serverless-offline

custom:
  dynamodb:
    stages:
      - dev
    start:
      port: 8000
      inMemory: true
      migrate: true
      seed: true
    seed:
      dev:
        sources:
          - table: Users
            sources: [seed-data/Users.json]	
          - table: Tweets
            sources: [seed-data/Tweets.json]

resources:
  Resources:
    UserTable:
      Type: "AWS::DynamoDB::Table"
      Properties:
        KeySchema:
          -
            AttributeName: handle
            KeyType: HASH
        AttributeDefinitions:
          -
            AttributeName: handle
            AttributeType: S
        ProvisionedThroughput:
          ReadCapacityUnits: 10
          WriteCapacityUnits: 10
        TableName: "Users"

    TweetsTable:
      Type: "AWS::DynamoDB::Table"
      Properties:
        KeySchema:
          -
            AttributeName: tweet_id
            KeyType: HASH
        AttributeDefinitions:
          -
            AttributeName: tweet_id
            AttributeType: S
          -
            AttributeName: handle
            AttributeType: S
          -
            AttributeName: retweet_count
            AttributeType: N
          -
            AttributeName: created_at
            AttributeType: S
        ProvisionedThroughput:
          ReadCapacityUnits: 10
          WriteCapacityUnits: 10
        TableName: "Tweets"
        GlobalSecondaryIndexes:
          -
            IndexName: top-index
            KeySchema:
              -
                AttributeName: handle
                KeyType: HASH
              -
                AttributeName: retweet_count
                KeyType: RANGE
            Projection:
              ProjectionType: ALL
            ProvisionedThroughput:
              ReadCapacityUnits: 50
              WriteCapacityUnits: 50
          -
            IndexName: tweet-index
            KeySchema:
              -
                AttributeName: handle
                KeyType: HASH
              -
                AttributeName: created_at
                KeyType: RANGE
            Projection:
              ProjectionType: ALL
            ProvisionedThroughput:
              ReadCapacityUnits: 50
              WriteCapacityUnits: 50
```

I'm getting the following logs:
```
$ C:\dev\github\serverless-graphql\app-backend\appsync\dynamo\node_modules\.bin\serverless offline start --verbose
Dynamodb Local Started, Visit: http://localhost:8000/shell
NetworkingError [ERR_INVALID_PROTOCOL]: Protocol "http:" not supported. Expected "https:": DynamoDB - Error - 
 
 Networking Error ----------------------------------------
 
  TypeError [ERR_INVALID_PROTOCOL]: Protocol "http:" not supported. Expected "https:"
      at new ClientRequest (_http_client.js:144:11)
      at Object.request (http.js:44:10)
      at features.constructor.handleRequest (C:\dev\github\serverless-graphql\app-backend\appsync\dynamo\node_modules\aws-sdk\lib\http\node.js:45:23)
      at executeSend (C:\dev\github\serverless-graphql\app-backend\appsync\dynamo\node_modules\aws-sdk\lib\event_listeners.js:348:29)
      at Request.SEND (C:\dev\github\serverless-graphql\app-backend\appsync\dynamo\node_modules\aws-sdk\lib\event_listeners.js:362:9)
      at Request.callListeners (C:\dev\github\serverless-graphql\app-backend\appsync\dynamo\node_modules\aws-sdk\lib\sequential_executor.js:102:18)  
      at Request.emit (C:\dev\github\serverless-graphql\app-backend\appsync\dynamo\node_modules\aws-sdk\lib\sequential_executor.js:78:10)
      at Request.emit (C:\dev\github\serverless-graphql\app-backend\appsync\dynamo\node_modules\aws-sdk\lib\request.js:688:14)
      at Request.transition (C:\dev\github\serverless-graphql\app-backend\appsync\dynamo\node_modules\aws-sdk\lib\request.js:22:10)
      at AcceptorStateMachine.runTo (C:\dev\github\serverless-graphql\app-backend\appsync\dynamo\node_modules\aws-sdk\lib\state_machine.js:14:12)
      at C:\dev\github\serverless-graphql\app-backend\appsync\dynamo\node_modules\aws-sdk\lib\state_machine.js:26:10
      at Request.<anonymous> (C:\dev\github\serverless-graphql\app-backend\appsync\dynamo\node_modules\aws-sdk\lib\request.js:38:9)
      at Request.<anonymous> (C:\dev\github\serverless-graphql\app-backend\appsync\dynamo\node_modules\aws-sdk\lib\request.js:690:12)
      at Request.callListeners (C:\dev\github\serverless-graphql\app-backend\appsync\dynamo\node_modules\aws-sdk\lib\sequential_executor.js:116:18)
      at callNextListener (C:\dev\github\serverless-graphql\app-backend\appsync\dynamo\node_modules\aws-sdk\lib\sequential_executor.js:96:12)
      at C:\dev\github\serverless-graphql\app-backend\appsync\dynamo\node_modules\aws-sdk\lib\event_listeners.js:247:9
      at finish (C:\dev\github\serverless-graphql\app-backend\appsync\dynamo\node_modules\aws-sdk\lib\config.js:386:7)
      at C:\dev\github\serverless-graphql\app-backend\appsync\dynamo\node_modules\aws-sdk\lib\config.js:404:9
      at Credentials.get (C:\dev\github\serverless-graphql\app-backend\appsync\dynamo\node_modules\aws-sdk\lib\credentials.js:127:7)
      at getAsyncCredentials (C:\dev\github\serverless-graphql\app-backend\appsync\dynamo\node_modules\aws-sdk\lib\config.js:398:24)
      at Config.getCredentials (C:\dev\github\serverless-graphql\app-backend\appsync\dynamo\node_modules\aws-sdk\lib\config.js:418:9)
      at Request.SIGN (C:\dev\github\serverless-graphql\app-backend\appsync\dynamo\node_modules\aws-sdk\lib\event_listeners.js:218:22)
      at Request.callListeners (C:\dev\github\serverless-graphql\app-backend\appsync\dynamo\node_modules\aws-sdk\lib\sequential_executor.js:102:18)
      at callNextListener (C:\dev\github\serverless-graphql\app-backend\appsync\dynamo\node_modules\aws-sdk\lib\sequential_executor.js:96:12)
      at Request.discoverEndpoint (C:\dev\github\serverless-graphql\app-backend\appsync\dynamo\node_modules\aws-sdk\lib\discover_endpoint.js:326:67)
      at Request.callListeners (C:\dev\github\serverless-graphql\app-backend\appsync\dynamo\node_modules\aws-sdk\lib\sequential_executor.js:102:18)
      at Request.emit (C:\dev\github\serverless-graphql\app-backend\appsync\dynamo\node_modules\aws-sdk\lib\sequential_executor.js:78:10)
      at Request.emit (C:\dev\github\serverless-graphql\app-backend\appsync\dynamo\node_modules\aws-sdk\lib\request.js:688:14)
      at Request.transition (C:\dev\github\serverless-graphql\app-backend\appsync\dynamo\node_modules\aws-sdk\lib\request.js:22:10)
      at AcceptorStateMachine.runTo (C:\dev\github\serverless-graphql\app-backend\appsync\dynamo\node_modules\aws-sdk\lib\state_machine.js:14:12)
      at C:\dev\github\serverless-graphql\app-backend\appsync\dynamo\node_modules\aws-sdk\lib\state_machine.js:26:10
      at Request.<anonymous> (C:\dev\github\serverless-graphql\app-backend\appsync\dynamo\node_modules\aws-sdk\lib\request.js:38:9)
      at Request.<anonymous> (C:\dev\github\serverless-graphql\app-backend\appsync\dynamo\node_modules\aws-sdk\lib\request.js:690:12)
      at Request.callListeners (C:\dev\github\serverless-graphql\app-backend\appsync\dynamo\node_modules\aws-sdk\lib\sequential_executor.js:116:18)
      at Timeout.callNextListener [as _onTimeout] (C:\dev\github\serverless-graphql\app-backend\appsync\dynamo\node_modules\aws-sdk\lib\sequential_executor.js:96:12) 
      at listOnTimeout (internal/timers.js:531:17)
      at processTimers (internal/timers.js:475:7)

     For debugging logs, run again after setting the "SLS_DEBUG=*" environment variable.

  Get Support --------------------------------------------
     Docs:          docs.serverless.com
     Bugs:          github.com/serverless/serverless/issues
     Issues:        forum.serverless.com

  Your Environment Information ---------------------------
     Operating System:          win32
     Node Version:              12.15.0
     Framework Version:         2.31.0 (local)
     Plugin Version:            4.5.2
     SDK Version:               4.2.2
     Components Version:        3.7.7
```

Since the call stack points to errors in the **aws-sdk** package, I'm thinking the error occurs in [this line](https://github.com/99x/serverless-dynamodb-local/blob/a32926bda40306e1839e4f5aaccdaee4c54f81ec/index.js#L185).

Has anyone encountered this issue before or know how to fix it?  Thanks!
