### ISSUE TITLE
Rely on docker for local dynamodb

### ISSUE THREAD

**Issue by jbremmer** [99xt/serverless-dynamodb-local#57]
Could this plugin switch to relying on docker or better yet docker-compose so I would have to have blobal JDK installation for DynamoDB?

**Comment by AshanFernando** [comment]
You should be able to use a docker container. Skip the first two steps(`sls dynamodb install` & `sls dynamodb start`) which installs and starts dynamodb locally. Declare a custom port if the container uses a different port than 8000 for dynamodb by configuring it in serverless.yml

**Comment by jbremmer** [comment]
That's how I'm doing this, would be nice though to have it in package.

**Comment by bebbi** [comment]
I'm using dockerized ddb and node app (combined in docker-compose).
Can I just use the "migrate" functionality of this plugin?
When entering the apps container and doing a `./node_modules/.bin/serverless dynamodb migrate`,
I get
`[SyntaxError: Unexpected token C]`

**Comment by bebbi** [comment]
Turns out the above syntax error is a side effect of a request that fails to reach ddb and returns `Cannot POST /`

**Comment by kjersten** [comment]
In case it's helpful to anyone coming from a Google search for "serverless dynamodb local with Docker",  this configuration let's you find the right docker container, skip the plugin's startup step and run a migration:

```yaml
custom:
  dynamodb:
    start:
      host: dynamo # or the name of your Dynamo docker container
      port: "8000" # the port of our Dynamo docker container
      noStart: true
      migrate: true
````

**Comment by cyberwombat** [comment]
I had to specify the image instead of host:
```yaml
custom:
  dynamodb:
    start:
      image: dynamo # or the name of your Dynamo docker container
      port: "8000" # the port of our Dynamo docker container
      noStart: true
      migrate: true
```

**Comment by AntonioCS** [comment]
@kjersten 
Thank you so much, your little snippet worked. 
One thing that bothers me is that I only have on file `serverless.yml`, so I am unsure how that change in `serverless.yml` will affect production. In production I just want all the custom stuff to be ignored.

**Comment by cyberwombat** [comment]
@AntonioCS you can specify which stage this runs on:
```
dynamodb:
  # If you only want to use DynamoDB Local in some stages, declare them here
    stages:
      - dev
```
Is that what you need?

**Comment by kazbeel** [comment]
I am running successfully a container with dynamodb-local. It also seems the migration and seed are correctly performed, but at the moment my tests run, they do not find any table. Here is the error I get:

> Cannot do operations on a non-existent table

I have checked the DB vía web and, certainly, there is nothing.

Has anyone a hint?

**Comment by AntonioCS** [comment]
@cyberwombat Thanks but I just created another `serverless.yml` file and just pass that to serveless with the `-c` option.

**Comment by jorchg** [comment]
> I am running successfully a container with dynamodb-local. It also seems the migration and seed are correctly performed, but at the moment my tests run, they do not find any table. Here is the error I get:
> 
> > Cannot do operations on a non-existent table
> 
> I have checked the DB vía web and, certainly, there is nothing.
> 
> Has anyone a hint?

I am also having this problem. The weird thing is that if I execute a shell in the container running the serverless application and run `sls dynamodb migrate --account local --port 8000 --host dynamodb` the output is:

```bash
Serverless: DynamoDB - Warn - table xxxxx already exists
Serverless: DynamoDB - Warn - table xxxxx already exists
Serverless: DynamoDB - Warn - table xxxxx already exists
```

But my app still says it does not have the tables created. Even, if I go to the shell, no table has been created. Very weird.

**Comment by cyberwombat** [comment]
@jorchg Could you have possibly installed DynamoDB local as well? Perhaps you have both a local instance and a docker instance running

**Comment by jorchg** [comment]
> @jorchg Could you have possibly installed DynamoDB local as well? Perhaps you have both a local instance and a docker instance running

I have just found that I have to start the dynamodb-local docker image with the `-inMemory` and `-sharedDb` options, in my `docker-compose.yml` file just like this:

```yaml
 dynamodb:
    image: 'amazon/dynamodb-local'
    ports:
      - '8000:8000'
    command: ["-jar", "DynamoDBLocal.jar", "-sharedDb", "-inMemory"]
```

That solved the problem :)
