### ISSUE TITLE
Stage functionality has changed

### ISSUE THREAD

**Issue by Si1kIfY** [99xt/serverless-dynamodb-local#66]
Stage used to be prepended to the table name, since the latest NPM update this is has changed:

Input:
```
sls dynamodb start -s local
```

Old output:
```
Dynamodb Local Started, Visit: http://localhost:8000/shell

Table creation completed for table: local-databaseName
```

New output:
```
Dynamodb Local Started, Visit: http://localhost:8000/shell

Table creation completed for table: -databaseName
```

Is it intended or a bug?

If intended how do I set a stage in my dynamodb names?

**Comment by Si1kIfY** [comment]
Looks like this was caused by #62 which was taken as intended?

AFAICT there doesn't seem to be another way to set the stage in DynamoDB names?

**Comment by Si1kIfY** [comment]
CC'ing @raphaelmun and @mjzone for discussion

**Comment by raphaelmun** [comment]
@Si1kIfY You can, actually, by setting a custom variable called table_prefix in your serverless.yml with the stage like this:

```yml
custom:
  dynamodb:
    start: # usual stuff here....
      port: 8000
      inMemory: true
      migration: true
    migration:
      table_prefix: local
```
