### ISSUE TITLE
Serverless Offline hangs on quit

### ISSUE THREAD

**Issue by jetako** [99xt/serverless-dynamodb-local#83]
When quitting a serverless offline session, it looks like the plugin attempts to restart DyanmoDB Local. This hangs the process indefinitely.

Console output:
```
^CServerless: Serverless Halting...
DynamoDB Local failed to start with code 130
```

serverless.yml:
```
plugins:
  - serverless-offline
  - serverless-dynamodb-local

custom:
  dynamodb:
    start:
      port: 8000
      inMemory: true
      migrate: true
```

Version 0.2.19
