### ISSUE TITLE
Missing ExecuteAll? Won't migrate...

### ISSUE THREAD

**Issue by TimothyDalbey** [99xt/serverless-dynamodb-local#84]
Hey!

So, somehow my version of dynamoDB local is now missing the executeALL function?  It's also refusing to load the migrations when I start the utility.

```
custom:
  dynamodb:
    start:
      port: 8001
      inMemory: true
      migration: true
    migration:
      table_prefix: ${opt:stage}
      dir: ./dynamolocal/migrations
```
The stage variable is set to local.  

Help!
